### ISSUE TITLE
about "announcement" function

### ISSUE THREAD

**Issue by praha38** [Meowhal/osu-ahr#11]
Hi, Meowhal.
I always appreciate your contribution, and I'm really happy that your work getting famous.

There's a `Lobby` section in `local.json(default.json)`
It looks like it can send message to lobby periodically, but I never saw it worked in any AHR lobby.

Does `Lobby` plugin have announcement function or not?
If it doesn't, Announcement function would be great to manage lobby.
I know there are many tasks you should add/fix first, so take it easy on this.

Always take care of COVID, Thank you.

**Comment by Meowhal** [comment]
At first, I had a plan to add regular announcement function that based on the time.
But while I was playing in the ahr lobby, I came to think that bot should be as quiet as possible.
Then I planned to limit it only when no one has seen the message in the lobby.
After all, I haven't touched it until now, because of my laziness. Only the remnants of the plan remain in the config file.

It's not difficult to implement the function that simply announce periodically.
I will remove the remnants and add the simple function to lobby keeper plugin after I'm done with current work .

**Comment by praha38** [comment]
> At first, I had a plan to add regular announcement function that based on the time.
> But while I was playing in the ahr lobby, I came to think that bot should be as quiet as possible.

Ah, yes. Bot need shut its "mouth" sometimes. It's a really good point.

Thanks for reply, Meowhal.
Have a good day/night.
