### ISSUE TITLE
is it possible? If so, how?

### ISSUE THREAD

**Issue by NickKruto** [Meowhal/osu-ahr#151]
![image](https://user-images.githubusercontent.com/98841244/198642849-a3c93858-85a0-4105-bfac-cba08f7f6525.png)

**Comment by xayanide** [comment]
It is possible, we just need to replace those `${CS}` and `${HP}` strings and set it with the available properties `BeatmapCache` gives us.

In your `config/local.json` file you have set the value of `map_description` property under the `MapChecker` object to
```json
    "MapChecker": {
      ...,
      "map_description": "[https://osu.ppy.sh/b/${map_id} ${title}] | Star rating: ${star} | Duration: ${length} | CS: ${cs} | HP: ${hp}"
    },
```
I'll just leave them as lowercase `${cs}` and `${hp}` in the config, they're case sensitive. If you want those variables uppercase, you change the regular expression in the code accordingly.

The method in `src/plugins/MapChecker.ts` which replaces those strings is under `getMapDescription()`.

```ts
  private getMapDescription(map: BeatmapCache, set: Beatmapset) {
    let desc = this.option.map_description;
    desc = desc.replace(/\$\{title\}/g, set.title);
    desc = desc.replace(/\$\{map_id\}/g, map.id.toString());
    desc = desc.replace(/\$\{beatmapset_id\}/g, set.id.toString());
    desc = desc.replace(/\$\{star\}/g, map.difficulty_rating.toFixed(2));
    desc = desc.replace(/\$\{length\}/g, secToTimeNotation(map.total_length));
    return desc;
  }
```

We add a line that reassigns the `desc` variable with the replaced string. To replace that string, we search for the string `${cs}` using regular expression and replace it with the selected beatmap's circle size property `map.cs` before sending or returning the beatmap description in-game.

Circle size is a number but the [String.prototype.replace()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) method's second parameter only accepts strings, to solve this we return it as a string using [Number.prototype.toString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString) method.

```diff
  private getMapDescription(map: BeatmapCache, set: Beatmapset) {
    let desc = this.option.map_description;
    desc = desc.replace(/\$\{title\}/g, set.title);
    desc = desc.replace(/\$\{map_id\}/g, map.id.toString());
    desc = desc.replace(/\$\{beatmapset_id\}/g, set.id.toString());
    desc = desc.replace(/\$\{star\}/g, map.difficulty_rating.toFixed(2));
    desc = desc.replace(/\$\{length\}/g, secToTimeNotation(map.total_length));
+   desc = desc.replace(/\$\{cs\}/g, map.cs.toString());
    return desc;
  }

```

For `HP` as the second line, the way for it is similar, we change the first argument which is the regular expression to search for `hp` instead and change the second argument inside the [String.prototype.replace()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) method to `map.drain`, return it as a string using [Number.prototype.toString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString) method.

```diff
  private getMapDescription(map: BeatmapCache, set: Beatmapset) {
    let desc = this.option.map_description;
    desc = desc.replace(/\$\{title\}/g, set.title);
    desc = desc.replace(/\$\{map_id\}/g, map.id.toString());
    desc = desc.replace(/\$\{beatmapset_id\}/g, set.id.toString());
    desc = desc.replace(/\$\{star\}/g, map.difficulty_rating.toFixed(2));
    desc = desc.replace(/\$\{length\}/g, secToTimeNotation(map.total_length));
    desc = desc.replace(/\$\{cs\}/g, map.cs.toString());
+   desc = desc.replace(/\$\{hp\}/g, map.drain.toString());
    return desc;
  }
```

Run `npm run build` to recompile the code then `npm run start` to start the bot.

My `config/local.json` is different so you will see `Star rating` and `Length` on the beatmap description shown in-game instead of `Star rating:` and `Duration:`.

Here is how it would look like in-game for me.

![screenshot063](https://user-images.githubusercontent.com/18362871/198859108-b5550490-023d-4d01-85fc-e89ed1707918.jpg)

**Comment by NickKruto** [comment]
![image](https://user-images.githubusercontent.com/98841244/198871977-705a1bb8-5742-4f26-8d46-52ce5e94b2f0.png)
ok. I added ar and bpm. and for od how?

**Comment by NickKruto** [comment]
> It is possible, we just need to replace those `${CS}` and `${HP}` strings and set it with the available properties `BeatmapCache` gives us.
> 
> In your `config/local.json` file you have set the value of `map_description` property under the `MapChecker` object to
> 
> ```json
>     "MapChecker": {
>       ...,
>       "map_description": "[https://osu.ppy.sh/b/${map_id} ${title}] | Star rating: ${star} | Duration: ${length} | CS: ${cs} | HP: ${hp}"
>     },
> ```
> 
> I'll just leave them as lowercase `${cs}` and `${hp}` in the config, they're case sensitive. If you want those variables uppercase, you change the regular expression in the code accordingly.
> 
> The method in `src/plugins/MapChecker.ts` which replaces those strings is under `getMapDescription()`.
> 
> ```ts
>   private getMapDescription(map: BeatmapCache, set: Beatmapset) {
>     let desc = this.option.map_description;
>     desc = desc.replace(/\$\{title\}/g, set.title);
>     desc = desc.replace(/\$\{map_id\}/g, map.id.toString());
>     desc = desc.replace(/\$\{beatmapset_id\}/g, set.id.toString());
>     desc = desc.replace(/\$\{star\}/g, map.difficulty_rating.toFixed(2));
>     desc = desc.replace(/\$\{length\}/g, secToTimeNotation(map.total_length));
>     return desc;
>   }
> ```
> 
> We add a line that reassigns the `desc` variable with the replaced string. To replace that string, we search for the string `${cs}` using regular expression and replace it with the selected beatmap's circle size property `map.cs` before sending or returning the beatmap description in-game.
> 
> Circle size is a number but the [String.prototype.replace()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) method's second parameter only accepts strings, to solve this we return it as a string using [Number.prototype.toString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString) method.
> 
> ```diff
>   private getMapDescription(map: BeatmapCache, set: Beatmapset) {
>     let desc = this.option.map_description;
>     desc = desc.replace(/\$\{title\}/g, set.title);
>     desc = desc.replace(/\$\{map_id\}/g, map.id.toString());
>     desc = desc.replace(/\$\{beatmapset_id\}/g, set.id.toString());
>     desc = desc.replace(/\$\{star\}/g, map.difficulty_rating.toFixed(2));
>     desc = desc.replace(/\$\{length\}/g, secToTimeNotation(map.total_length));
> +   desc = desc.replace(/\$\{cs\}/g, map.cs.toString());
>     return desc;
>   }
> ```
> 
> For `HP` as the second line, the way for it is similar, we change the first argument which is the regular expression to search for `hp` instead and change the second argument inside the [String.prototype.replace()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) method to `map.drain`, return it as a string using [Number.prototype.toString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString) method.
> 
> ```diff
>   private getMapDescription(map: BeatmapCache, set: Beatmapset) {
>     let desc = this.option.map_description;
>     desc = desc.replace(/\$\{title\}/g, set.title);
>     desc = desc.replace(/\$\{map_id\}/g, map.id.toString());
>     desc = desc.replace(/\$\{beatmapset_id\}/g, set.id.toString());
>     desc = desc.replace(/\$\{star\}/g, map.difficulty_rating.toFixed(2));
>     desc = desc.replace(/\$\{length\}/g, secToTimeNotation(map.total_length));
>     desc = desc.replace(/\$\{cs\}/g, map.cs.toString());
> +   desc = desc.replace(/\$\{hp\}/g, map.drain.toString());
>     return desc;
>   }
> ```
> 
> Run `npm run build` to recompile the code then `npm run start` to start the bot.
> 
> My `config/local.json` is different so you will see `Star rating` and `Length` on the beatmap description shown in-game instead of `Star rating:` and `Duration:`.
> 
> Here is how it would look like in-game for me.
> 
> ![screenshot063](https://user-images.githubusercontent.com/18362871/198859108-b5550490-023d-4d01-85fc-e89ed1707918.jpg)

![image](https://user-images.githubusercontent.com/98841244/198872636-bf6c327d-65da-4f37-ba3c-bd7c647c8369.png)
ok. I added ar and bpm. and for od how?

**Comment by Xayanide** [comment]
It is `map.difficulty_rating`, the `difficulty_rating` property.

> ![image](https://user-images.githubusercontent.com/98841244/198871977-705a1bb8-5742-4f26-8d46-52ce5e94b2f0.png) ok. I added ar and bpm. and for od how?

**Comment by xayanide** [comment]
> ![image](https://user-images.githubusercontent.com/98841244/198871977-705a1bb8-5742-4f26-8d46-52ce5e94b2f0.png) ok. I added ar and bpm. and for od how?

For `OD` or overall difficulty, it is the `accuracy` property, written as `map.accuracy` if you want to use it on your case.
