### ISSUE TITLE
wew is nice bot! so can u put development.json recommend settings?

### ISSUE THREAD

**Issue by weebskinosu** [Meowhal/osu-ahr#2]
idk how to set start timer...
it wait to long before room is start with someone not ready in room...

**Comment by Meowhal** [comment]
I am very happy to see that someone is using it.

The host can use "!start [sec]" command by chat.
when host said "!start 10", the bot says "!mp start 10" and the match start in 10 sec.

But The bot doesn't have auto-start timer.
why no auto-start timer? Because I thought The person responsible for starting the game is the current host, not the bot.
In addition, it is difficult for the bot to determine who does not have a map yet.

If you still need the auto-start feature, Please tell me in detail what kind of behavior is desirable.
For example, when does the timer start. After the match? After selecting a map? With host command?

Thank you for reading my poor English to the end.

**Comment by weebskinosu** [comment]
yep i need auto-start feature after After Selecting a map

like when im pick map then do mp !start 60 or someting....
because im lazy to type commands....

That Be Perfect (For Me...)

**Comment by Meowhal** [comment]
I added auto start timer and clearhost functions on the dev brach. (ver 1.1.2)
I haven't written enough test codes, so there must be bugs related to clearhost.
But I think you can try it out for testing.

You can activate the function by adding the followings to the development.json.
```json
{
  "irc": {
    "server" : "irc.ppy.sh",
    "nick" : "xxx",
    "opt": {
      "port" : 6667,
      "password" : "yyy"
    }
  },
  "AutoStartTimer": {
    "enabled": true,
    "doClearHost": true,
    "waitingTime": 60
  }
}
```

**Comment by weebskinosu** [comment]
wew is work but yep got bug :
everyone ready but is not start automatic :(

**Comment by Meowhal** [comment]
fixed that 
thanks for reporting

**Comment by weebskinosu** [comment]
one more bug
after !clearhost people can't do !skip

**Comment by Meowhal** [comment]
This is not a bug and works as specified.
You didn't mention anything about it.¯\_(ツ)_/¯

anyway, i will add this feature this week.

**Comment by weebskinosu** [comment]
oh sorry = = im bad but thanks for add that!! feature

**Comment by Meowhal** [comment]
I wrote the code. Maybe it will work.
Let me know if you have any problems.

**Comment by weebskinosu** [comment]
everytings is good 
Thanks....
Close issue
